# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: blank # the website title (if blank, full name will be used instead)
firstname: Omawu Diane
middlename: R.
lastname: Name
email: you@example.com
description: > # the ">" symbol means to ignore newlines until "footertext:"
  A simple, whitespace theme for academics. Based on [*folio](https://github.com/bogoli/-folio) design.
footertext: >
  Powered by <a href="https://jekyllrb.com/" target="blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="blank">GitHub Pages</a>.
  Photos from <a href="https://unsplash.com" target="blank">Unsplash</a>.
keywords: jekyll, jekyll-theme, academic-website, portfolio-website  # add your own keywords or leave empty

lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: ⚛️  # the emoji used as the favicon (alternatively, provide image name in /assets/img/)

url: https://odenobabor.github.io # the base hostname & protocol for your site
baseurl:  # the subpath of your site, e.g. /blog/
lastupdated: false # set to true if you want to display last updated in the footer
impressumpath:  # set to path to include impressum link in the footer, use the same path as permalink in a page, helps to conform with EU GDPR

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

# code highlighter theme
highlightthemelight: github   # https://github.com/jwarby/jekyll-pygments-themes
highlightthemedark: native    # https://github.com/jwarby/jekyll-pygments-themes

# repo color theme
repothemelight: default       # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repothemedark: dark           # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------
# will use title and url fields
# Take a look to https://github.com/jekyll/jekyll-feed for more customization

rssicon: true

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbarfixed: true
footerfixed: true

# Dimensions
max_width: 800px

# TODO: add layout settings (single page vs. multi-page)

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------
# Display links to the page with a preview object on social media.
serveogmeta: false # Include Open Graph meta tags in the HTML head
serveschemaorg: false # Include Schema.org in the HTML head
ogimage: # The site-wide (default for all links) Open Graph preview image

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

githubusername: # your GitHub user name
gitlabusername: # your GitLab user name
twitterusername: # your Twitter handle
linkedinusername: # your LinkedIn user name
scholaruserid: # your Google Scholar ID
orcidid: # your ORCID ID
mediumusername: # your Medium username
quorausername: # your Quora username
publonsid: # your ID on Publons
researchgateprofile: # your profile on ResearchGate
bloggerurl: # your blogger URL
workurl: # work page URL
keybaseusername: # your keybase user name
wikidataid: # your wikidata id
dblpurl: # your DBLP profile url
stackoverflowid: #your stackoverflow id

contactnote: >
  You can even add a little note about which of these is the best way to reach you.

# -----------------------------------------------------------------------------
# Analytics and search engine verification
# -----------------------------------------------------------------------------

googleanalytics:  # your Goole Analytics measurement ID (format: G-XXXXXXXXXX)
panelbearanalytics:  # panelbear analytics site ID (format: XXXXXXXXX)

googlesiteverification:  # your google-site-verification ID (Google Search Console)
bingsiteverification:  # out your bing-site-verification ID (Bing Webmaster)

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blogname: al-folio # blogname will be displayed in your blog page
blognavtitle: blog # your blog must have a title for it to be displayed in the nav bar
blogdescription: a simple whitespace theme for academics
permalink: /blog/:year/:title/

# Pagination
pagination:
  enabled: true

# Comments
disqusshortname: al-folio # put your disqus shortname
# https://help.disqus.com/en/articles/1717111-what-s-a-shortname

# External sources.
# If you have blog posts published on medium.com or other exteranl sources,
# you can display them in your blog by adding a link to the RSS feed.
externalsources:
  - name: medium.com
    rssurl: https://medium.com/@al-folio/feed

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

newsscrollable: true # adds a vertical scroll bar if there are more than 3 news items
newslimit: 5 # leave blank to include all the news in the `news` folder

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntaxhighlighteropts:
    cssclass: 'highlight'
    span:
      linenumbers: false
    block:
      linenumbers: false
      startline: 1

# Includes & excludes
include: ['pages']
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor
keepfiles:
  - CNAME
  - .nojekyll
  - .git

# Plug-ins
plugins:
  - jekyll-archives
  - jekyll-diagrams
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-imagemagick
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-target-blank
  - jekyll-twitter-plugin
  - jemoji

# Sitemap settings
defaults:
  - scope:
      path: "assets/**/*.*"
    values:
      sitemap: false

# -----------------------------------------------------------------------------
# Jekyll Minifier
# -----------------------------------------------------------------------------

jekyll-minifier:
  exclude: ['robots.txt']
  uglifierargs:
    harmony: true

# -----------------------------------------------------------------------------
# Jekyll Archives
# -----------------------------------------------------------------------------

jekyll-archives:
  enabled: [year, tags, categories] # enables year, tag and category archives (remove if you need to disable one of them).
  layouts:
    year: archive-year
    tag: archive-tag
    category: archive-category
  permalinks:
    year: '/blog/:year/'
    tag: '/blog/tag/:name/'
    category: '/blog/category/:name/'

displaytags: ['formatting', 'images', 'links', 'math', 'code'] # this tags will be dispalyed on the front page of your blog

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:

  lastname: Einstein
  firstname: [Albert, A.]

  style: apa
  locale: en

  source: /bibliography/
  bibliography: papers.bib
  bibliographytemplate: bib
  # Note: if you have latex math in your bibtex, the latex filter
  # preprocessing may conflict with MathJAX if the latter is enabled.
  # See https://github.com/alshedivat/al-folio/issues/357.
  bibtexfilters: [latex, smallcaps, superscript]

  replacestrings: true
  joinstrings: true

  detailsdir: bibliography
  detailslayout: bibtex.html
  detailslink: Details

  query: "@*"

# Filter out certain bibtex entry keywords used internally from the bib output
filteredbibtexkeywords: [abbr, abstract, arxiv, bibtexshow, html, pdf, selected, supp, blog, code, poster, slides, website, preview]

# Maximum number of authors to be shown, other authors will be visible on hover, leave blank to show all authors
maxauthorlimit: 3

# -----------------------------------------------------------------------------
# Responsive WebP Images
# -----------------------------------------------------------------------------

imagemagick:
  enabled: true # enables responsive images for your site (recomended, see https://github.com/alshedivat/al-folio/issues/537)
  widths:
    - 480
    - 800
    - 1400
  inputdirectories:
    - assets/img/
  inputformats:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".tiff"
  outputformats:
    webp: "-resize 800x"

# -----------------------------------------------------------------------------
# Jekyll Diagrams
# -----------------------------------------------------------------------------

jekyll-diagrams:
    # configuration, see https://github.com/zhustec/jekyll-diagrams.
    # feel free to comment out this section if not using jekyll diagrams.


# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enablegoogleanalytics:    false  # enables google analytics
enablepanelbearanalytics: false  # enables panelbear analytics
enablegoogleverification: false  # enables google site verification
enablebingverification:   false  # enables bing site verification
enablemasonry:             true   # enables automatic project cards arangement
enablemath:                true   # enables math typesetting (uses MathJax)
enabletooltips:            false  # enables automatic tooltip links generated
                                   # for each section titles on pages and posts
enabledarkmode:            true   # enables switching between light/dark modes
enablenavbarsocial:       false  # enables displaying social links in the
                                   # navbar on the about page
enableprojectcategories:  true   # enables categorization of projects into
                                   # multiple categories
enablemediumzoom:         true   # enables image zoom feature (as on medium.com)


# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------

academicons:
  version: "1.9.1"
  integrity: "sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg="
bootstrap:
  version: "4.6.1"
  integrity:
    css: "sha256-DF7Zhf293AJxJNTmh5zhoYYIMs2oXitRfBjY+9L//AY="
    js: "sha256-fgLAgv7fyCGopR/gBNq2iW3ZKIdqIcyshnUULC4vex8="
fontawesome:
  version: "5.15.4"
  integrity: "sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4="
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
mathjax:
  version: "3.2.0"
masonry:
  version: "4.2.2"
  integrity: "sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI="
mdb:
  version: "4.20.0"
  integrity:
    css: "sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw="
    js: "sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA="
mediumzoom:
  version: "1.0.6"
  integrity: "sha256-EdPgYcPk/IIrw7FYeuJQexva49pVRZNmt3LculEr7zM="
